
defaultRules:
  create: false 
alertmanager:
  enabled: false 
grafana:
  enabled: true
  adminPassword: "admin"
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.192.168.1.51.nip.io
prometheus:
  ingress:                  
    enabled: true           
    ingressClassName: traefik # 
    hosts:                  # 
      - prometheus.192.168.1.51.nip.io
  prometheusSpec:
    additionalScrapeConfigs: []
    additionalScrapeConfigsExternal: false
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi 
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1024Mi
    serviceMonitorSelectorNilUsesHelmValues: false