# prom-values.yaml
defaultRules:
  create: false 
alertmanager:
  enabled: false 
grafana:
  enabled: true
  adminPassword: "admin"
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.192.168.1.49.nip.io
prometheus:
  ingress:                  # ДОБАВЛЯЕМ ЭТОТ БЛОК
    enabled: true           # 
    ingressClassName: traefik # 
    hosts:                  # 
      - prometheus.192.168.1.49.nip.io # Адрес для прома
  prometheusSpec:
    additionalScrapeConfigs: []
    additionalScrapeConfigsExternal: false
    retention: 2d 
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1024Mi
    serviceMonitorSelectorNilUsesHelmValues: false