// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfDnsEventXdp struct {
	_     structs.HostLayout
	Event struct {
		_              structs.HostLayout
		QnameLen       uint8
		Qname          [256]uint8
		CompressionLen uint8
	}
	_         [6]byte
	LatencyNs uint64
	Status    uint8
	_         [7]byte
}

type BpfHashKey struct {
	_    structs.HostLayout
	Hash uint64
	TXID uint16
	IpV  uint16
	Ip   struct {
		_    structs.HostLayout
		Ipv4 uint32
		_    [12]byte
	}
	_ [4]byte
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	TcDnsEgress  *ebpf.ProgramSpec `ebpf:"tc_dns_egress"`
	TcDnsIngress *ebpf.ProgramSpec `ebpf:"tc_dns_ingress"`
	XdpWatch     *ebpf.ProgramSpec `ebpf:"xdp_watch"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	ConfigMap              *ebpf.MapSpec `ebpf:"config_map"`
	DnsEventRingbuf        *ebpf.MapSpec `ebpf:"dns_event_ringbuf"`
	DnsHashMap             *ebpf.MapSpec `ebpf:"dns_hash_map"`
	TcIngressScratchpadMap *ebpf.MapSpec `ebpf:"tc_ingress_scratchpad_map"`
	TcMetricsMap           *ebpf.MapSpec `ebpf:"tc_metrics_map"`
	XdpMetricsMap          *ebpf.MapSpec `ebpf:"xdp_metrics_map"`
	XdpScratchpadMap       *ebpf.MapSpec `ebpf:"xdp_scratchpad_map"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	ConfigMap              *ebpf.Map `ebpf:"config_map"`
	DnsEventRingbuf        *ebpf.Map `ebpf:"dns_event_ringbuf"`
	DnsHashMap             *ebpf.Map `ebpf:"dns_hash_map"`
	TcIngressScratchpadMap *ebpf.Map `ebpf:"tc_ingress_scratchpad_map"`
	TcMetricsMap           *ebpf.Map `ebpf:"tc_metrics_map"`
	XdpMetricsMap          *ebpf.Map `ebpf:"xdp_metrics_map"`
	XdpScratchpadMap       *ebpf.Map `ebpf:"xdp_scratchpad_map"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.ConfigMap,
		m.DnsEventRingbuf,
		m.DnsHashMap,
		m.TcIngressScratchpadMap,
		m.TcMetricsMap,
		m.XdpMetricsMap,
		m.XdpScratchpadMap,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	TcDnsEgress  *ebpf.Program `ebpf:"tc_dns_egress"`
	TcDnsIngress *ebpf.Program `ebpf:"tc_dns_ingress"`
	XdpWatch     *ebpf.Program `ebpf:"xdp_watch"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.TcDnsEgress,
		p.TcDnsIngress,
		p.XdpWatch,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
